### PR TITLE
[New Bees]

### PR DESCRIPTION
**Pull request by jtmnf**
- Added 3 new bees (**Endery** (30% - EnderPearl), **Enderie** (45% - EnderPearl) and **Dragony** (2% - DragonEgg));
- All the bees where tested and configured to not be overpowereded;

### CODE REVIEW

**Comment by jtmnf** [comment]
It's possible to change the rates (specially on the Enderie - instead of 45%, it's 35%)... But the stats are changed to so that's why I bumped it up to 45%!

**Comment by Lach01298** [comment]
I'm not sure how i feel about this as there is already a way to get ender pearls in forestry. but higher tier ender bees might bee nice and also infinite dragon eggs.

**Comment by jtmnf** [comment]
I saw that, but the bee can, probably, be available according to the configs (for example: easy ender pearls, or something like that) or tweaked (less chance of getting ender pearls - because it's direct and not by using the carpenter). By the way, I already made more 15 bees (all the colours, except lapis).

If you need help with the configs, I'm able to help!

**Comment by jtmnf** [comment]
For an easy view on the 15 new bees: http://i.imgur.com/Vgxi3zL.png

**Comment by jtmnf** [comment]
You should, at least, merge the colour bees, in my opinion... But it is your mod, you do what you want :)
Continue the good job 👍

**Pull request closed without merging**
